package nz.govt.linz.landonline.step.landonlite.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import java.sql.Timestamp;

@Entity
public class TitleJournal {
    @Id @GeneratedValue
    private long id;

    @Column(nullable = false)
    private Timestamp time;

    //WARNING: Spring/Hibernate (JPA) framework autogenerates a column for
    //  a foreign key (and subsequent entity class member) when
    //  @JoinColumn is used to create a @OneToMany association.
    //  When using @JoinColumn, best to explicitly specify the foreign key
    //  column name instead of leaving it to Hibernate to create one (in
    //  such instances, Hibernate uses the entity/table name suffixed with
    //  the primary key).
    //  So, for an entity/class called Foo, with an @Id of key, it results in
    //  the following member being autogenerated:
    //      FOO_KEY
    //  This means the default foreign key column in our instance would be:
    //      TITLE_ID
    //  which is already being used for Title Number/Identifier.
    //
    //UPDATE: Even though I explicitly specified 'TITLE_FKEY' as the foreign
    //  key column name, Hiberate still implicitly autogenerates a TITLE_ID
    //  column (and titleId entity member) !??
    //  ...so using titleNumber/TITLE_NUMBER instead

    private String titleNumber;
    private String description;
    private String ownerName;

    @ManyToOne
    @JoinColumn(name = "title_id")
    private Title title;

    public TitleJournal() {
    }

    public TitleJournal(Title t) {
        titleNumber = t.getTitleNumber();
        description = t.getDescription();
        ownerName = t.getOwnerName();
        time = new Timestamp(System.currentTimeMillis());
        title = t;
    }

    // No setters, journal entries are read-only

    public long getId() {
        return id;
    }

    public String getTitleNumber() {
        return titleNumber;
    }

    public String getDescription() {
        return description;
    }

    public String getOwnerName() {
        return ownerName;
    }

    public Timestamp getTime() {
        return time;
    }

    @Override
    public String toString() {
        return "TitleJournal{" +
                "id=" + id +
                ", title.id=" + title.getId() +
                ", time=" + time +
                ", titleNumber='" + titleNumber + '\'' +
                ", description='" + description + '\'' +
                ", ownerName='" + ownerName + '\'' +
                '}';
    }
}
